#!/usr/bin/env bash

clear
source_dir="$HOME/maps/emacs_mini_source"
function install-emacs-mini {
    git clone git://git.savannah.gnu.org/emacs.git $source_dir
    cd "$source_dir"/maps/emacs_mini_source || exit
    $source_dir/autogen.sh
    $source_dir/configure                    
        --without-all                    \
        --without-x                      \
        --prefix="$HOME"/maps/emacs_mini \
    CFLAGS='-Os -m32'
    make
    make install
}
