#!/usr/bin/env python3

import sys
from os import system
from random import randint as r
from datetime import datetime

system("clear")
sys.tracebacklimit = 0

time = datetime.now()
time_str = time.strftime("%d/%m/%y, %H:%M:%S")

page = r(39, 292)
path = "/home/jerry/ran.txt"

# with open(path)

ranFile = open(path, "a")
ranFile.write(f"{time_str} >> página {page}\n")
print(f"\n {time_str}: página {page}")
ranFile.close()
