/home/jerry/Music/Toss_A_Coin_To_Your_Witcher2.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-01-Silver.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-02-Nocturnal_Me.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-03-Crystal_Days.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-04-The_Yo-Yo_Man.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-05-Thorn_of_Crowns.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-06-The_Killing_Moon.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-07-Seven_Seas.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-08-My_Kingdom.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-09-Ocean_Rain.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-10-Angels_and_Devils-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-11-All_You_Need_Is_Love-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-12-The_Killing_Moon-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-13-Stars_Are_Stars-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-14-Villiers_Terrace-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-15-Silver-#-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-16-My_Kingdom-Live-#-.mp3
/home/jerry/Music/Echo_And_The_Bunnymen/Echo_and_The_Bunnymen-2002-Ocean_Rain/Echo_and_the_Bunnymen-Ocean_Rain-Bonus_Tracks-17-Ocean_Rain-Live-#-.mp3
