/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/01-The_Art_of_Fugue,BWV_1080-Contrapunctus_1.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/02-The_Art_of_Fugue,BWV_1080-Contrapunctus_2.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/03-The_Art_of_Fugue,BWV_1080-Contrapunctus_3.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/04-The_Art_of_Fugue,BWV_1080-Contrapunctus_4.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/05-The_Art_of_Fugue,BWV_1080-Contrapunctus_5.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/06-The_Art_of_Fugue,BWV_1080-Contrapunctus_6-a_4,im_Stile_francese-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/07-The_Art_of_Fugue,BWV_1080-Contrapunctus_7-a_4,per_Augmentationem_et_Diminuotionem-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/08-The_Art_of_Fugue,BWV_1080-Contrapunctus_8-a_3-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/09-The_Art_of_Fugue,BWV_1080-Contrapunctus_9-a_4,alla_Duodecima-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/10-The_Art_of_Fugue,BWV_1080-Contrapunctus_10-a_4,alla_Decima-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/11-The_Art_of_Fugue,BWV_1080-Contrapunctus_11-a_4-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/12-The_Art_of_Fugue,BWV_1080-Canon_alla_Ottava.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/13-The_Art_of_Fugue,BWV_1080-Canon_alla_Duodecima-in_Contrapuncto_alla_Quinta-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/14-The_Art_of_Fugue,BWV_1080-Canon_alla_Decima-Contrapuncto_all_Terza-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/15-The_Art_of_Fugue,BWV_1080-Canon-per_Augmentationem_in_contrario_motu-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/16-The_Art_of_Fugue,BWV_1080-Contrapunctus_13-a_3-rectus-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/17-The_Art_of_Fugue,BWV_1080-Contrapunctus_13-a_3-inversus-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/18-The_Art_of_Fugue,BWV_1080-Contrapunctus_12-a_4-rectus-.mp3
/home/jerry/Music/Classical/Bach/Bach_Complete/MP3/11_CD13_Bach_The_Art_of_Fugue/19-The_Art_of_Fugue,BWV_1080-Contrapunctus_12-a_4-inversus-.mp3
