#!/bin/bash

commit="$*"

clear
echo ""
echo "#adding all files#"
echo ""
git add -A
echo ""
echo "#commiting and pushing"#
echo ""
echo "commit message:" $commit
git commit -am "$commit" && git push
echo ""