#!/usr/bin/env bash

message="$1"
time="$2"

clear
termdown --no-figlet -T "$message" "$time" &&  play --no-show-progress "$HOME"/Sounds/apple.mp3 &&
echo "" &&
echo ' ' $message 'TIMER FINISHED' &&
echo ""
