#!/usr/bin/env bash

# 1. List tasks

printf "\n"

~/maps/t/t.py --task-dir ~/org/Data/.t_tasks --list tasks

# 2. Get task id
printf "\n Please type the ID of the task you wish to delete\n "

read ID

~/maps/t/t.py --task-dir ~/org/Data/.t_tasks -f "$ID"

output_formatting
output="$(~/maps/t/t.py --task-dir ~/org/Data/.t_tasks --list tasks)"

printf "\ $s": "$output"

