#!/bin/bash

clear
# pkill -fi "emacs --daemon=gui-emacs" &&
emacsclient --socket-name=gui-emacs --eval '(save-buffers-kill-emacs)' &&
clear
ps ax | pgrep -v grep | egrep -i 'emacs --daemon=gui-emacs'

