#!/bin/bash

clear
echo " "
echo " killing emacs"
echo " "
emacsclient --socket-name=gui-emacs --eval '(save-buffers-kill-emacs)' &>/dev/null &&
echo " "
echo " starting server"
echo " "
"$HOME"/scripts/emacs_scripts/lif
