#!/usr/bin/env bash

clear
printf "\n   This will ALLOW you from changing your Emacs configuration files."
printf "\n   Dou you really wanna do that?\n\n"
read -rp "   PRESS ENTER TO CONTINUE"
read -rp "   ARE YOU SURE?"
read -rp "   You really shouldn't do that, you now..."
read -rp "   ARE YOU 100% FUCKING SURE?"
read -rp "   REALLY?"
read -rp "   LAST CHANCE..."
read -rp "   Okay, then... I did my bit!"
result=$(chmod +w "$HOME"/.emacs.d/init.org "$HOME"/.emacs.d/init.el)
echo "$result"

