#!/usr/bin/env bash

# basic packages

clear

apt -y update && apt -y dist-upgrade &&
    apt -y install i3 i3status rofi neovim lxappearance calibre zathura zathura-pdf-poppler xclip dmenu unclutter trash-cli arandr xbindkeys font-manager silversearcher-ag xsel xdotool lxde-settings-daemon wget curl cmus keepassxc
