#!/bin/bash

i3-msg [class="Slack"] move scratchpad &>/dev/null &&
i3-msg [title="mrblack"] move scratchpad &>/dev/null &&
i3-msg [title="term-ranger"] move scratchpad &>/dev/null &&
i3-msg [title="term-bpython"] move scratchpad &>/dev/null &&
i3-msg [title="term-up"] scratchpad show &>/dev/null &&
xdotool key --clearmodifiers --delay 24 Ctrl+l Ctrl+a Ctrl+k Ctrl+Shift+v
